version: '3.8'
services:
  api:
    build: .
    ports:
      - 8081:8080
    environment:
      - IS_MASTER=false
  api_master:
    build: .
    ports:
      - 8080:8080
    environment:
      - IS_MASTER=true
    # depends_on:
    #   - api